// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_cnn_Pipeline_VITIS_LOOP_21_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        local_input_31_address0,
        local_input_31_ce0,
        local_input_31_we0,
        local_input_31_d0,
        local_input_32_address0,
        local_input_32_ce0,
        local_input_32_we0,
        local_input_32_d0,
        local_input_33_address0,
        local_input_33_ce0,
        local_input_33_we0,
        local_input_33_d0,
        local_input_34_address0,
        local_input_34_ce0,
        local_input_34_we0,
        local_input_34_d0,
        local_input_35_address0,
        local_input_35_ce0,
        local_input_35_we0,
        local_input_35_d0,
        local_input_36_address0,
        local_input_36_ce0,
        local_input_36_we0,
        local_input_36_d0,
        local_input_37_address0,
        local_input_37_ce0,
        local_input_37_we0,
        local_input_37_d0,
        local_input_38_address0,
        local_input_38_ce0,
        local_input_38_we0,
        local_input_38_d0,
        local_input_39_address0,
        local_input_39_ce0,
        local_input_39_we0,
        local_input_39_d0,
        local_input_40_address0,
        local_input_40_ce0,
        local_input_40_we0,
        local_input_40_d0,
        local_input_41_address0,
        local_input_41_ce0,
        local_input_41_we0,
        local_input_41_d0,
        local_input_42_address0,
        local_input_42_ce0,
        local_input_42_we0,
        local_input_42_d0,
        local_input_43_address0,
        local_input_43_ce0,
        local_input_43_we0,
        local_input_43_d0,
        local_input_44_address0,
        local_input_44_ce0,
        local_input_44_we0,
        local_input_44_d0,
        local_input_45_address0,
        local_input_45_ce0,
        local_input_45_we0,
        local_input_45_d0,
        local_input_46_address0,
        local_input_46_ce0,
        local_input_46_we0,
        local_input_46_d0,
        local_input_47_address0,
        local_input_47_ce0,
        local_input_47_we0,
        local_input_47_d0,
        local_input_48_address0,
        local_input_48_ce0,
        local_input_48_we0,
        local_input_48_d0,
        local_input_49_address0,
        local_input_49_ce0,
        local_input_49_we0,
        local_input_49_d0,
        local_input_50_address0,
        local_input_50_ce0,
        local_input_50_we0,
        local_input_50_d0,
        local_input_51_address0,
        local_input_51_ce0,
        local_input_51_we0,
        local_input_51_d0,
        local_input_52_address0,
        local_input_52_ce0,
        local_input_52_we0,
        local_input_52_d0,
        local_input_53_address0,
        local_input_53_ce0,
        local_input_53_we0,
        local_input_53_d0,
        local_input_54_address0,
        local_input_54_ce0,
        local_input_54_we0,
        local_input_54_d0,
        local_input_55_address0,
        local_input_55_ce0,
        local_input_55_we0,
        local_input_55_d0,
        local_input_56_address0,
        local_input_56_ce0,
        local_input_56_we0,
        local_input_56_d0,
        local_input_57_address0,
        local_input_57_ce0,
        local_input_57_we0,
        local_input_57_d0,
        local_input_58_address0,
        local_input_58_ce0,
        local_input_58_we0,
        local_input_58_d0,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        input_r_address1,
        input_r_ce1,
        input_r_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] local_input_31_address0;
output   local_input_31_ce0;
output   local_input_31_we0;
output  [15:0] local_input_31_d0;
output  [3:0] local_input_32_address0;
output   local_input_32_ce0;
output   local_input_32_we0;
output  [15:0] local_input_32_d0;
output  [3:0] local_input_33_address0;
output   local_input_33_ce0;
output   local_input_33_we0;
output  [15:0] local_input_33_d0;
output  [3:0] local_input_34_address0;
output   local_input_34_ce0;
output   local_input_34_we0;
output  [15:0] local_input_34_d0;
output  [3:0] local_input_35_address0;
output   local_input_35_ce0;
output   local_input_35_we0;
output  [15:0] local_input_35_d0;
output  [3:0] local_input_36_address0;
output   local_input_36_ce0;
output   local_input_36_we0;
output  [15:0] local_input_36_d0;
output  [3:0] local_input_37_address0;
output   local_input_37_ce0;
output   local_input_37_we0;
output  [15:0] local_input_37_d0;
output  [3:0] local_input_38_address0;
output   local_input_38_ce0;
output   local_input_38_we0;
output  [15:0] local_input_38_d0;
output  [3:0] local_input_39_address0;
output   local_input_39_ce0;
output   local_input_39_we0;
output  [15:0] local_input_39_d0;
output  [3:0] local_input_40_address0;
output   local_input_40_ce0;
output   local_input_40_we0;
output  [15:0] local_input_40_d0;
output  [3:0] local_input_41_address0;
output   local_input_41_ce0;
output   local_input_41_we0;
output  [15:0] local_input_41_d0;
output  [3:0] local_input_42_address0;
output   local_input_42_ce0;
output   local_input_42_we0;
output  [15:0] local_input_42_d0;
output  [3:0] local_input_43_address0;
output   local_input_43_ce0;
output   local_input_43_we0;
output  [15:0] local_input_43_d0;
output  [3:0] local_input_44_address0;
output   local_input_44_ce0;
output   local_input_44_we0;
output  [15:0] local_input_44_d0;
output  [3:0] local_input_45_address0;
output   local_input_45_ce0;
output   local_input_45_we0;
output  [15:0] local_input_45_d0;
output  [3:0] local_input_46_address0;
output   local_input_46_ce0;
output   local_input_46_we0;
output  [15:0] local_input_46_d0;
output  [3:0] local_input_47_address0;
output   local_input_47_ce0;
output   local_input_47_we0;
output  [15:0] local_input_47_d0;
output  [3:0] local_input_48_address0;
output   local_input_48_ce0;
output   local_input_48_we0;
output  [15:0] local_input_48_d0;
output  [3:0] local_input_49_address0;
output   local_input_49_ce0;
output   local_input_49_we0;
output  [15:0] local_input_49_d0;
output  [3:0] local_input_50_address0;
output   local_input_50_ce0;
output   local_input_50_we0;
output  [15:0] local_input_50_d0;
output  [3:0] local_input_51_address0;
output   local_input_51_ce0;
output   local_input_51_we0;
output  [15:0] local_input_51_d0;
output  [3:0] local_input_52_address0;
output   local_input_52_ce0;
output   local_input_52_we0;
output  [15:0] local_input_52_d0;
output  [3:0] local_input_53_address0;
output   local_input_53_ce0;
output   local_input_53_we0;
output  [15:0] local_input_53_d0;
output  [3:0] local_input_54_address0;
output   local_input_54_ce0;
output   local_input_54_we0;
output  [15:0] local_input_54_d0;
output  [3:0] local_input_55_address0;
output   local_input_55_ce0;
output   local_input_55_we0;
output  [15:0] local_input_55_d0;
output  [3:0] local_input_56_address0;
output   local_input_56_ce0;
output   local_input_56_we0;
output  [15:0] local_input_56_d0;
output  [3:0] local_input_57_address0;
output   local_input_57_ce0;
output   local_input_57_we0;
output  [15:0] local_input_57_d0;
output  [3:0] local_input_58_address0;
output   local_input_58_ce0;
output   local_input_58_we0;
output  [15:0] local_input_58_d0;
output  [9:0] input_r_address0;
output   input_r_ce0;
input  [15:0] input_r_q0;
output  [9:0] input_r_address1;
output   input_r_ce1;
input  [15:0] input_r_q1;

reg ap_idle;
reg local_input_31_ce0;
reg local_input_31_we0;
reg local_input_32_ce0;
reg local_input_32_we0;
reg local_input_33_ce0;
reg local_input_33_we0;
reg local_input_34_ce0;
reg local_input_34_we0;
reg local_input_35_ce0;
reg local_input_35_we0;
reg local_input_36_ce0;
reg local_input_36_we0;
reg local_input_37_ce0;
reg local_input_37_we0;
reg local_input_38_ce0;
reg local_input_38_we0;
reg local_input_39_ce0;
reg local_input_39_we0;
reg local_input_40_ce0;
reg local_input_40_we0;
reg local_input_41_ce0;
reg local_input_41_we0;
reg local_input_42_ce0;
reg local_input_42_we0;
reg local_input_43_ce0;
reg local_input_43_we0;
reg local_input_44_ce0;
reg local_input_44_we0;
reg local_input_45_ce0;
reg local_input_45_we0;
reg local_input_46_ce0;
reg local_input_46_we0;
reg local_input_47_ce0;
reg local_input_47_we0;
reg local_input_48_ce0;
reg local_input_48_we0;
reg local_input_49_ce0;
reg local_input_49_we0;
reg local_input_50_ce0;
reg local_input_50_we0;
reg local_input_51_ce0;
reg local_input_51_we0;
reg local_input_52_ce0;
reg local_input_52_we0;
reg local_input_53_ce0;
reg local_input_53_we0;
reg local_input_54_ce0;
reg local_input_54_we0;
reg local_input_55_ce0;
reg local_input_55_we0;
reg local_input_56_ce0;
reg local_input_56_we0;
reg local_input_57_ce0;
reg local_input_57_we0;
reg local_input_58_ce0;
reg local_input_58_we0;
reg input_r_ce0;
reg input_r_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln21_fu_569_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] j_22_reg_609;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln21_fu_575_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln21_1_fu_592_p1;
reg   [4:0] j_fu_112;
wire   [4:0] add_ln21_fu_580_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_j_22;
wire   [4:0] or_ln21_fu_586_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 j_fu_112 = 5'd0;
#0 ap_done_reg = 1'b0;
end

cnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln21_fu_569_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_112 <= add_ln21_fu_580_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_112 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_22_reg_609 <= ap_sig_allocacmp_j_22;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_569_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_22 = 5'd0;
    end else begin
        ap_sig_allocacmp_j_22 = j_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_ce1 = 1'b1;
    end else begin
        input_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_31_ce0 = 1'b1;
    end else begin
        local_input_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_31_we0 = 1'b1;
    end else begin
        local_input_31_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_32_ce0 = 1'b1;
    end else begin
        local_input_32_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_32_we0 = 1'b1;
    end else begin
        local_input_32_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_33_ce0 = 1'b1;
    end else begin
        local_input_33_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_33_we0 = 1'b1;
    end else begin
        local_input_33_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_34_ce0 = 1'b1;
    end else begin
        local_input_34_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_34_we0 = 1'b1;
    end else begin
        local_input_34_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_35_ce0 = 1'b1;
    end else begin
        local_input_35_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_35_we0 = 1'b1;
    end else begin
        local_input_35_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_36_ce0 = 1'b1;
    end else begin
        local_input_36_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_36_we0 = 1'b1;
    end else begin
        local_input_36_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_37_ce0 = 1'b1;
    end else begin
        local_input_37_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_37_we0 = 1'b1;
    end else begin
        local_input_37_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_38_ce0 = 1'b1;
    end else begin
        local_input_38_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_38_we0 = 1'b1;
    end else begin
        local_input_38_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_39_ce0 = 1'b1;
    end else begin
        local_input_39_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd8) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_39_we0 = 1'b1;
    end else begin
        local_input_39_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_40_ce0 = 1'b1;
    end else begin
        local_input_40_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd8) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_40_we0 = 1'b1;
    end else begin
        local_input_40_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_41_ce0 = 1'b1;
    end else begin
        local_input_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd10) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_41_we0 = 1'b1;
    end else begin
        local_input_41_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_42_ce0 = 1'b1;
    end else begin
        local_input_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd10) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_42_we0 = 1'b1;
    end else begin
        local_input_42_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_43_ce0 = 1'b1;
    end else begin
        local_input_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd12) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_43_we0 = 1'b1;
    end else begin
        local_input_43_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_44_ce0 = 1'b1;
    end else begin
        local_input_44_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd12) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_44_we0 = 1'b1;
    end else begin
        local_input_44_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_45_ce0 = 1'b1;
    end else begin
        local_input_45_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd14) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_45_we0 = 1'b1;
    end else begin
        local_input_45_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_46_ce0 = 1'b1;
    end else begin
        local_input_46_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd14) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_46_we0 = 1'b1;
    end else begin
        local_input_46_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_47_ce0 = 1'b1;
    end else begin
        local_input_47_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_47_we0 = 1'b1;
    end else begin
        local_input_47_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_48_ce0 = 1'b1;
    end else begin
        local_input_48_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_48_we0 = 1'b1;
    end else begin
        local_input_48_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_49_ce0 = 1'b1;
    end else begin
        local_input_49_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd18) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_49_we0 = 1'b1;
    end else begin
        local_input_49_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_50_ce0 = 1'b1;
    end else begin
        local_input_50_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd18) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_50_we0 = 1'b1;
    end else begin
        local_input_50_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_51_ce0 = 1'b1;
    end else begin
        local_input_51_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd20) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_51_we0 = 1'b1;
    end else begin
        local_input_51_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_52_ce0 = 1'b1;
    end else begin
        local_input_52_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd20) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_52_we0 = 1'b1;
    end else begin
        local_input_52_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_53_ce0 = 1'b1;
    end else begin
        local_input_53_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd22) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_53_we0 = 1'b1;
    end else begin
        local_input_53_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_54_ce0 = 1'b1;
    end else begin
        local_input_54_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd22) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_54_we0 = 1'b1;
    end else begin
        local_input_54_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_55_ce0 = 1'b1;
    end else begin
        local_input_55_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd24) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_55_we0 = 1'b1;
    end else begin
        local_input_55_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_56_ce0 = 1'b1;
    end else begin
        local_input_56_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (j_22_reg_609 == 5'd24) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_56_we0 = 1'b1;
    end else begin
        local_input_56_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_57_ce0 = 1'b1;
    end else begin
        local_input_57_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(j_22_reg_609 == 5'd0) & ~(j_22_reg_609 == 5'd2) & ~(j_22_reg_609 == 5'd4) & ~(j_22_reg_609 == 5'd6) & ~(j_22_reg_609 == 5'd8) & ~(j_22_reg_609 == 5'd10) & ~(j_22_reg_609 == 5'd12) & ~(j_22_reg_609 == 5'd14) & ~(j_22_reg_609 == 5'd16) & ~(j_22_reg_609 == 5'd18) & ~(j_22_reg_609 == 5'd20) & ~(j_22_reg_609 == 5'd22) & ~(j_22_reg_609 == 5'd24) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_57_we0 = 1'b1;
    end else begin
        local_input_57_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_58_ce0 = 1'b1;
    end else begin
        local_input_58_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(j_22_reg_609 == 5'd0) & ~(j_22_reg_609 == 5'd2) & ~(j_22_reg_609 == 5'd4) & ~(j_22_reg_609 == 5'd6) & ~(j_22_reg_609 == 5'd8) & ~(j_22_reg_609 == 5'd10) & ~(j_22_reg_609 == 5'd12) & ~(j_22_reg_609 == 5'd14) & ~(j_22_reg_609 == 5'd16) & ~(j_22_reg_609 == 5'd18) & ~(j_22_reg_609 == 5'd20) & ~(j_22_reg_609 == 5'd22) & ~(j_22_reg_609 == 5'd24) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_input_58_we0 = 1'b1;
    end else begin
        local_input_58_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_fu_580_p2 = (ap_sig_allocacmp_j_22 + 5'd2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln21_fu_569_p2 = ((ap_sig_allocacmp_j_22 < 5'd28) ? 1'b1 : 1'b0);

assign input_r_address0 = zext_ln21_1_fu_592_p1;

assign input_r_address1 = zext_ln21_fu_575_p1;

assign local_input_31_address0 = 64'd0;

assign local_input_31_d0 = input_r_q1;

assign local_input_32_address0 = 64'd0;

assign local_input_32_d0 = input_r_q0;

assign local_input_33_address0 = 64'd0;

assign local_input_33_d0 = input_r_q1;

assign local_input_34_address0 = 64'd0;

assign local_input_34_d0 = input_r_q0;

assign local_input_35_address0 = 64'd0;

assign local_input_35_d0 = input_r_q1;

assign local_input_36_address0 = 64'd0;

assign local_input_36_d0 = input_r_q0;

assign local_input_37_address0 = 64'd0;

assign local_input_37_d0 = input_r_q1;

assign local_input_38_address0 = 64'd0;

assign local_input_38_d0 = input_r_q0;

assign local_input_39_address0 = 64'd0;

assign local_input_39_d0 = input_r_q1;

assign local_input_40_address0 = 64'd0;

assign local_input_40_d0 = input_r_q0;

assign local_input_41_address0 = 64'd0;

assign local_input_41_d0 = input_r_q1;

assign local_input_42_address0 = 64'd0;

assign local_input_42_d0 = input_r_q0;

assign local_input_43_address0 = 64'd0;

assign local_input_43_d0 = input_r_q1;

assign local_input_44_address0 = 64'd0;

assign local_input_44_d0 = input_r_q0;

assign local_input_45_address0 = 64'd0;

assign local_input_45_d0 = input_r_q1;

assign local_input_46_address0 = 64'd0;

assign local_input_46_d0 = input_r_q0;

assign local_input_47_address0 = 64'd0;

assign local_input_47_d0 = input_r_q1;

assign local_input_48_address0 = 64'd0;

assign local_input_48_d0 = input_r_q0;

assign local_input_49_address0 = 64'd0;

assign local_input_49_d0 = input_r_q1;

assign local_input_50_address0 = 64'd0;

assign local_input_50_d0 = input_r_q0;

assign local_input_51_address0 = 64'd0;

assign local_input_51_d0 = input_r_q1;

assign local_input_52_address0 = 64'd0;

assign local_input_52_d0 = input_r_q0;

assign local_input_53_address0 = 64'd0;

assign local_input_53_d0 = input_r_q1;

assign local_input_54_address0 = 64'd0;

assign local_input_54_d0 = input_r_q0;

assign local_input_55_address0 = 64'd0;

assign local_input_55_d0 = input_r_q1;

assign local_input_56_address0 = 64'd0;

assign local_input_56_d0 = input_r_q0;

assign local_input_57_address0 = 64'd0;

assign local_input_57_d0 = input_r_q1;

assign local_input_58_address0 = 64'd0;

assign local_input_58_d0 = input_r_q0;

assign or_ln21_fu_586_p2 = (ap_sig_allocacmp_j_22 | 5'd1);

assign zext_ln21_1_fu_592_p1 = or_ln21_fu_586_p2;

assign zext_ln21_fu_575_p1 = ap_sig_allocacmp_j_22;

endmodule //cnn_cnn_Pipeline_VITIS_LOOP_21_2
