-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_cnn_Pipeline_VITIS_LOOP_21_223 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    local_input_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_1_ce0 : OUT STD_LOGIC;
    local_input_1_we0 : OUT STD_LOGIC;
    local_input_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_2_ce0 : OUT STD_LOGIC;
    local_input_2_we0 : OUT STD_LOGIC;
    local_input_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_3_ce0 : OUT STD_LOGIC;
    local_input_3_we0 : OUT STD_LOGIC;
    local_input_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_4_ce0 : OUT STD_LOGIC;
    local_input_4_we0 : OUT STD_LOGIC;
    local_input_4_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_5_ce0 : OUT STD_LOGIC;
    local_input_5_we0 : OUT STD_LOGIC;
    local_input_5_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_6_ce0 : OUT STD_LOGIC;
    local_input_6_we0 : OUT STD_LOGIC;
    local_input_6_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_7_ce0 : OUT STD_LOGIC;
    local_input_7_we0 : OUT STD_LOGIC;
    local_input_7_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_8_ce0 : OUT STD_LOGIC;
    local_input_8_we0 : OUT STD_LOGIC;
    local_input_8_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_9_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_9_ce0 : OUT STD_LOGIC;
    local_input_9_we0 : OUT STD_LOGIC;
    local_input_9_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_10_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_10_ce0 : OUT STD_LOGIC;
    local_input_10_we0 : OUT STD_LOGIC;
    local_input_10_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_11_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_11_ce0 : OUT STD_LOGIC;
    local_input_11_we0 : OUT STD_LOGIC;
    local_input_11_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_12_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_12_ce0 : OUT STD_LOGIC;
    local_input_12_we0 : OUT STD_LOGIC;
    local_input_12_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_13_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_13_ce0 : OUT STD_LOGIC;
    local_input_13_we0 : OUT STD_LOGIC;
    local_input_13_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_14_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_14_ce0 : OUT STD_LOGIC;
    local_input_14_we0 : OUT STD_LOGIC;
    local_input_14_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_15_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_15_ce0 : OUT STD_LOGIC;
    local_input_15_we0 : OUT STD_LOGIC;
    local_input_15_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_16_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_16_ce0 : OUT STD_LOGIC;
    local_input_16_we0 : OUT STD_LOGIC;
    local_input_16_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_17_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_17_ce0 : OUT STD_LOGIC;
    local_input_17_we0 : OUT STD_LOGIC;
    local_input_17_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_18_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_18_ce0 : OUT STD_LOGIC;
    local_input_18_we0 : OUT STD_LOGIC;
    local_input_18_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_19_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_19_ce0 : OUT STD_LOGIC;
    local_input_19_we0 : OUT STD_LOGIC;
    local_input_19_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_20_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_20_ce0 : OUT STD_LOGIC;
    local_input_20_we0 : OUT STD_LOGIC;
    local_input_20_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_21_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_21_ce0 : OUT STD_LOGIC;
    local_input_21_we0 : OUT STD_LOGIC;
    local_input_21_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_22_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_22_ce0 : OUT STD_LOGIC;
    local_input_22_we0 : OUT STD_LOGIC;
    local_input_22_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_23_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_23_ce0 : OUT STD_LOGIC;
    local_input_23_we0 : OUT STD_LOGIC;
    local_input_23_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_24_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_24_ce0 : OUT STD_LOGIC;
    local_input_24_we0 : OUT STD_LOGIC;
    local_input_24_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_25_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_25_ce0 : OUT STD_LOGIC;
    local_input_25_we0 : OUT STD_LOGIC;
    local_input_25_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_26_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_26_ce0 : OUT STD_LOGIC;
    local_input_26_we0 : OUT STD_LOGIC;
    local_input_26_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_27_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_27_ce0 : OUT STD_LOGIC;
    local_input_27_we0 : OUT STD_LOGIC;
    local_input_27_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_28_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_28_ce0 : OUT STD_LOGIC;
    local_input_28_we0 : OUT STD_LOGIC;
    local_input_28_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_r_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    input_r_ce1 : OUT STD_LOGIC;
    input_r_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of cnn_cnn_Pipeline_VITIS_LOOP_21_223 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv10_284 : STD_LOGIC_VECTOR (9 downto 0) := "1010000100";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln21_fu_573_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal j_19_reg_633 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln23_30_fu_589_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln23_32_fu_616_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_116 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln21_fu_594_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_19 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln23_fu_579_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln23_fu_583_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln21_fu_600_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln23_31_fu_606_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln23_9_fu_610_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component cnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    j_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln21_fu_573_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_116 <= add_ln21_fu_594_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_116 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                j_19_reg_633 <= ap_sig_allocacmp_j_19;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln21_fu_594_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_19) + unsigned(ap_const_lv5_2));
    add_ln23_9_fu_610_p2 <= std_logic_vector(unsigned(zext_ln23_31_fu_606_p1) + unsigned(ap_const_lv10_284));
    add_ln23_fu_583_p2 <= std_logic_vector(unsigned(zext_ln23_fu_579_p1) + unsigned(ap_const_lv10_284));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln21_fu_573_p2)
    begin
        if (((icmp_ln21_fu_573_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_19_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_116, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_19 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_j_19 <= j_fu_116;
        end if; 
    end process;

    icmp_ln21_fu_573_p2 <= "1" when (unsigned(ap_sig_allocacmp_j_19) < unsigned(ap_const_lv5_1C)) else "0";
    input_r_address0 <= zext_ln23_32_fu_616_p1(10 - 1 downto 0);
    input_r_address1 <= zext_ln23_30_fu_589_p1(10 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_r_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_ce1 <= ap_const_logic_1;
        else 
            input_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_10_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_10_ce0 <= ap_const_logic_1;
        else 
            local_input_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_10_d0 <= input_r_q0;

    local_input_10_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_8) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_10_we0 <= ap_const_logic_1;
        else 
            local_input_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_11_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_11_ce0 <= ap_const_logic_1;
        else 
            local_input_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_11_d0 <= input_r_q1;

    local_input_11_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_A) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_11_we0 <= ap_const_logic_1;
        else 
            local_input_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_12_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_12_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_12_ce0 <= ap_const_logic_1;
        else 
            local_input_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_12_d0 <= input_r_q0;

    local_input_12_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_A) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_12_we0 <= ap_const_logic_1;
        else 
            local_input_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_13_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_13_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_13_ce0 <= ap_const_logic_1;
        else 
            local_input_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_13_d0 <= input_r_q1;

    local_input_13_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_C) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_13_we0 <= ap_const_logic_1;
        else 
            local_input_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_14_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_14_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_14_ce0 <= ap_const_logic_1;
        else 
            local_input_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_14_d0 <= input_r_q0;

    local_input_14_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_C) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_14_we0 <= ap_const_logic_1;
        else 
            local_input_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_15_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_15_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_15_ce0 <= ap_const_logic_1;
        else 
            local_input_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_15_d0 <= input_r_q1;

    local_input_15_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_E) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_15_we0 <= ap_const_logic_1;
        else 
            local_input_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_16_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_16_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_16_ce0 <= ap_const_logic_1;
        else 
            local_input_16_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_16_d0 <= input_r_q0;

    local_input_16_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_E) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_16_we0 <= ap_const_logic_1;
        else 
            local_input_16_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_17_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_17_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_17_ce0 <= ap_const_logic_1;
        else 
            local_input_17_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_17_d0 <= input_r_q1;

    local_input_17_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_10) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_17_we0 <= ap_const_logic_1;
        else 
            local_input_17_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_18_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_18_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_18_ce0 <= ap_const_logic_1;
        else 
            local_input_18_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_18_d0 <= input_r_q0;

    local_input_18_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_10) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_18_we0 <= ap_const_logic_1;
        else 
            local_input_18_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_19_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_19_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_19_ce0 <= ap_const_logic_1;
        else 
            local_input_19_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_19_d0 <= input_r_q1;

    local_input_19_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_12) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_19_we0 <= ap_const_logic_1;
        else 
            local_input_19_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_1_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_1_ce0 <= ap_const_logic_1;
        else 
            local_input_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_1_d0 <= input_r_q1;

    local_input_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_1_we0 <= ap_const_logic_1;
        else 
            local_input_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_20_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_20_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_20_ce0 <= ap_const_logic_1;
        else 
            local_input_20_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_20_d0 <= input_r_q0;

    local_input_20_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_12) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_20_we0 <= ap_const_logic_1;
        else 
            local_input_20_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_21_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_21_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_21_ce0 <= ap_const_logic_1;
        else 
            local_input_21_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_21_d0 <= input_r_q1;

    local_input_21_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_14) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_21_we0 <= ap_const_logic_1;
        else 
            local_input_21_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_22_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_22_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_22_ce0 <= ap_const_logic_1;
        else 
            local_input_22_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_22_d0 <= input_r_q0;

    local_input_22_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_14) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_22_we0 <= ap_const_logic_1;
        else 
            local_input_22_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_23_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_23_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_23_ce0 <= ap_const_logic_1;
        else 
            local_input_23_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_23_d0 <= input_r_q1;

    local_input_23_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_23_we0 <= ap_const_logic_1;
        else 
            local_input_23_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_24_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_24_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_24_ce0 <= ap_const_logic_1;
        else 
            local_input_24_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_24_d0 <= input_r_q0;

    local_input_24_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_24_we0 <= ap_const_logic_1;
        else 
            local_input_24_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_25_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_25_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_25_ce0 <= ap_const_logic_1;
        else 
            local_input_25_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_25_d0 <= input_r_q1;

    local_input_25_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_18) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_25_we0 <= ap_const_logic_1;
        else 
            local_input_25_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_26_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_26_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_26_ce0 <= ap_const_logic_1;
        else 
            local_input_26_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_26_d0 <= input_r_q0;

    local_input_26_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_18) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_26_we0 <= ap_const_logic_1;
        else 
            local_input_26_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_27_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_27_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_27_ce0 <= ap_const_logic_1;
        else 
            local_input_27_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_27_d0 <= input_r_q1;

    local_input_27_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if ((not((j_19_reg_633 = ap_const_lv5_0)) and not((j_19_reg_633 = ap_const_lv5_2)) and not((j_19_reg_633 = ap_const_lv5_4)) and not((j_19_reg_633 = ap_const_lv5_6)) and not((j_19_reg_633 = ap_const_lv5_8)) and not((j_19_reg_633 = ap_const_lv5_A)) and not((j_19_reg_633 = ap_const_lv5_C)) and not((j_19_reg_633 = ap_const_lv5_E)) and not((j_19_reg_633 = ap_const_lv5_10)) and not((j_19_reg_633 = ap_const_lv5_12)) and not((j_19_reg_633 = ap_const_lv5_14)) and not((j_19_reg_633 = ap_const_lv5_16)) and not((j_19_reg_633 = ap_const_lv5_18)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_27_we0 <= ap_const_logic_1;
        else 
            local_input_27_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_28_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_28_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_28_ce0 <= ap_const_logic_1;
        else 
            local_input_28_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_28_d0 <= input_r_q0;

    local_input_28_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if ((not((j_19_reg_633 = ap_const_lv5_0)) and not((j_19_reg_633 = ap_const_lv5_2)) and not((j_19_reg_633 = ap_const_lv5_4)) and not((j_19_reg_633 = ap_const_lv5_6)) and not((j_19_reg_633 = ap_const_lv5_8)) and not((j_19_reg_633 = ap_const_lv5_A)) and not((j_19_reg_633 = ap_const_lv5_C)) and not((j_19_reg_633 = ap_const_lv5_E)) and not((j_19_reg_633 = ap_const_lv5_10)) and not((j_19_reg_633 = ap_const_lv5_12)) and not((j_19_reg_633 = ap_const_lv5_14)) and not((j_19_reg_633 = ap_const_lv5_16)) and not((j_19_reg_633 = ap_const_lv5_18)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_28_we0 <= ap_const_logic_1;
        else 
            local_input_28_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_2_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_2_ce0 <= ap_const_logic_1;
        else 
            local_input_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_2_d0 <= input_r_q0;

    local_input_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_2_we0 <= ap_const_logic_1;
        else 
            local_input_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_3_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_3_ce0 <= ap_const_logic_1;
        else 
            local_input_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_3_d0 <= input_r_q1;

    local_input_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_3_we0 <= ap_const_logic_1;
        else 
            local_input_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_4_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_4_ce0 <= ap_const_logic_1;
        else 
            local_input_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_4_d0 <= input_r_q0;

    local_input_4_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_4_we0 <= ap_const_logic_1;
        else 
            local_input_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_5_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_5_ce0 <= ap_const_logic_1;
        else 
            local_input_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_5_d0 <= input_r_q1;

    local_input_5_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_5_we0 <= ap_const_logic_1;
        else 
            local_input_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_6_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_6_ce0 <= ap_const_logic_1;
        else 
            local_input_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_6_d0 <= input_r_q0;

    local_input_6_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_6_we0 <= ap_const_logic_1;
        else 
            local_input_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_7_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_7_ce0 <= ap_const_logic_1;
        else 
            local_input_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_7_d0 <= input_r_q1;

    local_input_7_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_7_we0 <= ap_const_logic_1;
        else 
            local_input_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_8_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_8_ce0 <= ap_const_logic_1;
        else 
            local_input_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_8_d0 <= input_r_q0;

    local_input_8_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_8_we0 <= ap_const_logic_1;
        else 
            local_input_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_9_address0 <= ap_const_lv64_8(4 - 1 downto 0);

    local_input_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_9_ce0 <= ap_const_logic_1;
        else 
            local_input_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_9_d0 <= input_r_q1;

    local_input_9_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_19_reg_633, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_19_reg_633 = ap_const_lv5_8) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_9_we0 <= ap_const_logic_1;
        else 
            local_input_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln21_fu_600_p2 <= (ap_sig_allocacmp_j_19 or ap_const_lv5_1);
    zext_ln23_30_fu_589_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln23_fu_583_p2),64));
    zext_ln23_31_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln21_fu_600_p2),10));
    zext_ln23_32_fu_616_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln23_9_fu_610_p2),64));
    zext_ln23_fu_579_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j_19),10));
end behav;
