-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_cnn_Pipeline_VITIS_LOOP_21_21 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    local_input_61_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_61_ce0 : OUT STD_LOGIC;
    local_input_61_we0 : OUT STD_LOGIC;
    local_input_61_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_62_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_62_ce0 : OUT STD_LOGIC;
    local_input_62_we0 : OUT STD_LOGIC;
    local_input_62_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_63_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_63_ce0 : OUT STD_LOGIC;
    local_input_63_we0 : OUT STD_LOGIC;
    local_input_63_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_64_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_64_ce0 : OUT STD_LOGIC;
    local_input_64_we0 : OUT STD_LOGIC;
    local_input_64_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_65_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_65_ce0 : OUT STD_LOGIC;
    local_input_65_we0 : OUT STD_LOGIC;
    local_input_65_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_66_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_66_ce0 : OUT STD_LOGIC;
    local_input_66_we0 : OUT STD_LOGIC;
    local_input_66_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_67_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_67_ce0 : OUT STD_LOGIC;
    local_input_67_we0 : OUT STD_LOGIC;
    local_input_67_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_68_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_68_ce0 : OUT STD_LOGIC;
    local_input_68_we0 : OUT STD_LOGIC;
    local_input_68_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_69_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_69_ce0 : OUT STD_LOGIC;
    local_input_69_we0 : OUT STD_LOGIC;
    local_input_69_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_70_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_70_ce0 : OUT STD_LOGIC;
    local_input_70_we0 : OUT STD_LOGIC;
    local_input_70_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_71_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_71_ce0 : OUT STD_LOGIC;
    local_input_71_we0 : OUT STD_LOGIC;
    local_input_71_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_72_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_72_ce0 : OUT STD_LOGIC;
    local_input_72_we0 : OUT STD_LOGIC;
    local_input_72_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_73_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_73_ce0 : OUT STD_LOGIC;
    local_input_73_we0 : OUT STD_LOGIC;
    local_input_73_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_74_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_74_ce0 : OUT STD_LOGIC;
    local_input_74_we0 : OUT STD_LOGIC;
    local_input_74_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_75_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_75_ce0 : OUT STD_LOGIC;
    local_input_75_we0 : OUT STD_LOGIC;
    local_input_75_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_76_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_76_ce0 : OUT STD_LOGIC;
    local_input_76_we0 : OUT STD_LOGIC;
    local_input_76_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_77_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_77_ce0 : OUT STD_LOGIC;
    local_input_77_we0 : OUT STD_LOGIC;
    local_input_77_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_78_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_78_ce0 : OUT STD_LOGIC;
    local_input_78_we0 : OUT STD_LOGIC;
    local_input_78_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_79_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_79_ce0 : OUT STD_LOGIC;
    local_input_79_we0 : OUT STD_LOGIC;
    local_input_79_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_80_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_80_ce0 : OUT STD_LOGIC;
    local_input_80_we0 : OUT STD_LOGIC;
    local_input_80_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_81_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_81_ce0 : OUT STD_LOGIC;
    local_input_81_we0 : OUT STD_LOGIC;
    local_input_81_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_82_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_82_ce0 : OUT STD_LOGIC;
    local_input_82_we0 : OUT STD_LOGIC;
    local_input_82_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_83_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_83_ce0 : OUT STD_LOGIC;
    local_input_83_we0 : OUT STD_LOGIC;
    local_input_83_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_84_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_84_ce0 : OUT STD_LOGIC;
    local_input_84_we0 : OUT STD_LOGIC;
    local_input_84_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_85_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_85_ce0 : OUT STD_LOGIC;
    local_input_85_we0 : OUT STD_LOGIC;
    local_input_85_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_86_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_86_ce0 : OUT STD_LOGIC;
    local_input_86_we0 : OUT STD_LOGIC;
    local_input_86_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_87_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_87_ce0 : OUT STD_LOGIC;
    local_input_87_we0 : OUT STD_LOGIC;
    local_input_87_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    local_input_88_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_input_88_ce0 : OUT STD_LOGIC;
    local_input_88_we0 : OUT STD_LOGIC;
    local_input_88_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    input_r_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    input_r_ce1 : OUT STD_LOGIC;
    input_r_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of cnn_cnn_Pipeline_VITIS_LOOP_21_21 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln21_fu_571_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal j_reg_631 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln23_73_fu_587_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln23_75_fu_614_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_fu_114 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln21_fu_592_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln23_fu_577_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln23_fu_581_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln21_fu_598_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln23_74_fu_604_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln23_1_fu_608_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component cnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    j_1_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln21_fu_571_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_1_fu_114 <= add_ln21_fu_592_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_1_fu_114 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                j_reg_631 <= ap_sig_allocacmp_j;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln21_fu_592_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j) + unsigned(ap_const_lv5_2));
    add_ln23_1_fu_608_p2 <= std_logic_vector(unsigned(zext_ln23_74_fu_604_p1) + unsigned(ap_const_lv6_1C));
    add_ln23_fu_581_p2 <= std_logic_vector(unsigned(zext_ln23_fu_577_p1) + unsigned(ap_const_lv6_1C));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln21_fu_571_p2)
    begin
        if (((icmp_ln21_fu_571_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_1_fu_114, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_j <= j_1_fu_114;
        end if; 
    end process;

    icmp_ln21_fu_571_p2 <= "1" when (unsigned(ap_sig_allocacmp_j) < unsigned(ap_const_lv5_1C)) else "0";
    input_r_address0 <= zext_ln23_75_fu_614_p1(10 - 1 downto 0);
    input_r_address1 <= zext_ln23_73_fu_587_p1(10 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_r_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_ce1 <= ap_const_logic_1;
        else 
            input_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_61_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_61_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_61_ce0 <= ap_const_logic_1;
        else 
            local_input_61_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_61_d0 <= input_r_q1;

    local_input_61_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_61_we0 <= ap_const_logic_1;
        else 
            local_input_61_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_62_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_62_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_62_ce0 <= ap_const_logic_1;
        else 
            local_input_62_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_62_d0 <= input_r_q0;

    local_input_62_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_62_we0 <= ap_const_logic_1;
        else 
            local_input_62_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_63_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_63_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_63_ce0 <= ap_const_logic_1;
        else 
            local_input_63_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_63_d0 <= input_r_q1;

    local_input_63_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_63_we0 <= ap_const_logic_1;
        else 
            local_input_63_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_64_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_64_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_64_ce0 <= ap_const_logic_1;
        else 
            local_input_64_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_64_d0 <= input_r_q0;

    local_input_64_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_64_we0 <= ap_const_logic_1;
        else 
            local_input_64_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_65_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_65_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_65_ce0 <= ap_const_logic_1;
        else 
            local_input_65_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_65_d0 <= input_r_q1;

    local_input_65_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_65_we0 <= ap_const_logic_1;
        else 
            local_input_65_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_66_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_66_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_66_ce0 <= ap_const_logic_1;
        else 
            local_input_66_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_66_d0 <= input_r_q0;

    local_input_66_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_66_we0 <= ap_const_logic_1;
        else 
            local_input_66_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_67_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_67_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_67_ce0 <= ap_const_logic_1;
        else 
            local_input_67_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_67_d0 <= input_r_q1;

    local_input_67_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_67_we0 <= ap_const_logic_1;
        else 
            local_input_67_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_68_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_68_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_68_ce0 <= ap_const_logic_1;
        else 
            local_input_68_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_68_d0 <= input_r_q0;

    local_input_68_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_68_we0 <= ap_const_logic_1;
        else 
            local_input_68_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_69_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_69_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_69_ce0 <= ap_const_logic_1;
        else 
            local_input_69_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_69_d0 <= input_r_q1;

    local_input_69_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_8) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_69_we0 <= ap_const_logic_1;
        else 
            local_input_69_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_70_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_70_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_70_ce0 <= ap_const_logic_1;
        else 
            local_input_70_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_70_d0 <= input_r_q0;

    local_input_70_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_8) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_70_we0 <= ap_const_logic_1;
        else 
            local_input_70_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_71_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_71_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_71_ce0 <= ap_const_logic_1;
        else 
            local_input_71_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_71_d0 <= input_r_q1;

    local_input_71_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_A) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_71_we0 <= ap_const_logic_1;
        else 
            local_input_71_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_72_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_72_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_72_ce0 <= ap_const_logic_1;
        else 
            local_input_72_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_72_d0 <= input_r_q0;

    local_input_72_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_A) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_72_we0 <= ap_const_logic_1;
        else 
            local_input_72_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_73_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_73_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_73_ce0 <= ap_const_logic_1;
        else 
            local_input_73_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_73_d0 <= input_r_q1;

    local_input_73_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_C) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_73_we0 <= ap_const_logic_1;
        else 
            local_input_73_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_74_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_74_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_74_ce0 <= ap_const_logic_1;
        else 
            local_input_74_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_74_d0 <= input_r_q0;

    local_input_74_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_C) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_74_we0 <= ap_const_logic_1;
        else 
            local_input_74_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_75_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_75_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_75_ce0 <= ap_const_logic_1;
        else 
            local_input_75_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_75_d0 <= input_r_q1;

    local_input_75_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_E) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_75_we0 <= ap_const_logic_1;
        else 
            local_input_75_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_76_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_76_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_76_ce0 <= ap_const_logic_1;
        else 
            local_input_76_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_76_d0 <= input_r_q0;

    local_input_76_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_E) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_76_we0 <= ap_const_logic_1;
        else 
            local_input_76_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_77_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_77_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_77_ce0 <= ap_const_logic_1;
        else 
            local_input_77_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_77_d0 <= input_r_q1;

    local_input_77_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_10) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_77_we0 <= ap_const_logic_1;
        else 
            local_input_77_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_78_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_78_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_78_ce0 <= ap_const_logic_1;
        else 
            local_input_78_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_78_d0 <= input_r_q0;

    local_input_78_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_10) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_78_we0 <= ap_const_logic_1;
        else 
            local_input_78_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_79_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_79_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_79_ce0 <= ap_const_logic_1;
        else 
            local_input_79_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_79_d0 <= input_r_q1;

    local_input_79_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_12) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_79_we0 <= ap_const_logic_1;
        else 
            local_input_79_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_80_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_80_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_80_ce0 <= ap_const_logic_1;
        else 
            local_input_80_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_80_d0 <= input_r_q0;

    local_input_80_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_12) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_80_we0 <= ap_const_logic_1;
        else 
            local_input_80_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_81_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_81_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_81_ce0 <= ap_const_logic_1;
        else 
            local_input_81_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_81_d0 <= input_r_q1;

    local_input_81_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_14) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_81_we0 <= ap_const_logic_1;
        else 
            local_input_81_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_82_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_82_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_82_ce0 <= ap_const_logic_1;
        else 
            local_input_82_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_82_d0 <= input_r_q0;

    local_input_82_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_14) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_82_we0 <= ap_const_logic_1;
        else 
            local_input_82_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_83_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_83_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_83_ce0 <= ap_const_logic_1;
        else 
            local_input_83_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_83_d0 <= input_r_q1;

    local_input_83_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_83_we0 <= ap_const_logic_1;
        else 
            local_input_83_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_84_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_84_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_84_ce0 <= ap_const_logic_1;
        else 
            local_input_84_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_84_d0 <= input_r_q0;

    local_input_84_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_16) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_84_we0 <= ap_const_logic_1;
        else 
            local_input_84_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_85_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_85_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_85_ce0 <= ap_const_logic_1;
        else 
            local_input_85_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_85_d0 <= input_r_q1;

    local_input_85_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_18) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_85_we0 <= ap_const_logic_1;
        else 
            local_input_85_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_86_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_86_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_86_ce0 <= ap_const_logic_1;
        else 
            local_input_86_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_86_d0 <= input_r_q0;

    local_input_86_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (j_reg_631 = ap_const_lv5_18) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_86_we0 <= ap_const_logic_1;
        else 
            local_input_86_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_87_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_87_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_87_ce0 <= ap_const_logic_1;
        else 
            local_input_87_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_87_d0 <= input_r_q1;

    local_input_87_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if ((not((j_reg_631 = ap_const_lv5_0)) and not((j_reg_631 = ap_const_lv5_2)) and not((j_reg_631 = ap_const_lv5_4)) and not((j_reg_631 = ap_const_lv5_6)) and not((j_reg_631 = ap_const_lv5_8)) and not((j_reg_631 = ap_const_lv5_A)) and not((j_reg_631 = ap_const_lv5_C)) and not((j_reg_631 = ap_const_lv5_E)) and not((j_reg_631 = ap_const_lv5_10)) and not((j_reg_631 = ap_const_lv5_12)) and not((j_reg_631 = ap_const_lv5_14)) and not((j_reg_631 = ap_const_lv5_16)) and not((j_reg_631 = ap_const_lv5_18)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_87_we0 <= ap_const_logic_1;
        else 
            local_input_87_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_88_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    local_input_88_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_88_ce0 <= ap_const_logic_1;
        else 
            local_input_88_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_input_88_d0 <= input_r_q0;

    local_input_88_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, j_reg_631, ap_block_pp0_stage0_11001)
    begin
        if ((not((j_reg_631 = ap_const_lv5_0)) and not((j_reg_631 = ap_const_lv5_2)) and not((j_reg_631 = ap_const_lv5_4)) and not((j_reg_631 = ap_const_lv5_6)) and not((j_reg_631 = ap_const_lv5_8)) and not((j_reg_631 = ap_const_lv5_A)) and not((j_reg_631 = ap_const_lv5_C)) and not((j_reg_631 = ap_const_lv5_E)) and not((j_reg_631 = ap_const_lv5_10)) and not((j_reg_631 = ap_const_lv5_12)) and not((j_reg_631 = ap_const_lv5_14)) and not((j_reg_631 = ap_const_lv5_16)) and not((j_reg_631 = ap_const_lv5_18)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_input_88_we0 <= ap_const_logic_1;
        else 
            local_input_88_we0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln21_fu_598_p2 <= (ap_sig_allocacmp_j or ap_const_lv5_1);
    zext_ln23_73_fu_587_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln23_fu_581_p2),64));
    zext_ln23_74_fu_604_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln21_fu_598_p2),6));
    zext_ln23_75_fu_614_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln23_1_fu_608_p2),64));
    zext_ln23_fu_577_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j),6));
end behav;
